In [1]:
import torch
import torch.nn as nn


In [2]:
bi_grus = torch.nn.GRU(input_size=1, hidden_size=1, num_layers=1, batch_first=True, bidirectional=True)

reverse_gru = torch.nn.GRU(input_size=1, hidden_size=1, num_layers=1, batch_first=True, bidirectional=False)

normal_gru = torch.nn.GRU(input_size=1, hidden_size=1, num_layers=1, batch_first=True, bidirectional=False)

In [3]:
reverse_gru.weight_ih_l0 = bi_grus.weight_ih_l0_reverse
reverse_gru.weight_hh_l0 = bi_grus.weight_hh_l0_reverse
reverse_gru.bias_ih_l0 = bi_grus.bias_ih_l0_reverse
reverse_gru.bias_hh_l0 = bi_grus.bias_hh_l0_reverse

In [4]:
normal_gru.weight_ih_l0 = bi_grus.weight_ih_l0
normal_gru.weight_hh_l0 = bi_grus.weight_hh_l0
normal_gru.bias_ih_l0 = bi_grus.bias_ih_l0
normal_gru.bias_hh_l0 = bi_grus.bias_hh_l0

In [12]:
random_input = torch.randn(1, 3, 1)

In [43]:
def reverse_sequence(tensor):
    idx = [i for i in range(tensor.size(1)-1, -1, -1)]
    idx = torch.LongTensor(idx)
    return tensor.index_select(1, idx)    

In [44]:
inverted_tensor = reverse_sequence(random_input)

In [51]:
inverted_tensor

tensor([[[-1.4922],
         [-0.0991],
         [-0.3009]]])

In [58]:
bi_output, bi_hidden = bi_grus(random_input)
normal_output, normal_hidden = normal_gru(random_input)
reverse_output, reverse_hidden = reverse_gru(inverted_tensor)

In [59]:
reverse_sequence(reverse_output)

tensor([[[0.4031],
         [0.3404],
         [0.1040]]], grad_fn=<IndexSelectBackward>)

In [60]:
normal_output

tensor([[[0.5116],
         [0.7006],
         [0.8691]]], grad_fn=<TransposeBackward1>)

In [61]:
bi_output

tensor([[[0.5116, 0.4031],
         [0.7006, 0.3404],
         [0.8691, 0.1040]]], grad_fn=<TransposeBackward1>)

In [62]:
bi_output.shape

torch.Size([1, 3, 2])

In [64]:
torch.cat((normal_output,reverse_sequence(reverse_output)),-1)

tensor([[[0.5116, 0.4031],
         [0.7006, 0.3404],
         [0.8691, 0.1040]]], grad_fn=<CatBackward>)

In [117]:
layers = [3*2**x for x in range(9)]

In [121]:
[3*2**x for x in range(8)]

[3, 6, 12, 24, 48, 96, 192, 384]

In [119]:
[3*4**x for x in range(5)]

[3, 12, 48, 192, 768]

In [ ]:
[3, 3, 6, 6, 12, 12, 24, 48, 96, 192, 384, 768]

In [ ]:
[100, 400, 600, 768]